### ISSUE TITLE
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)

### ISSUE THREAD

**Issue by reneweteling** [qrpike/spotify-playlist-downloader#13]
Hey there,

Nice app btw. only im receiving an error when trying to download a link.

```
Downloader App Started..
 - Getting Playlist Data
 - Got Playlist: OLD SCHOOL HIP HOP
 - Processing 100 Tracks
/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                                  ^
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2321:27)
  at [object Object].Message.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:51)
  at Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/schemas.js:98:39)
  at Spotify._parse (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:1288:20)
  at parseData (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:592:18)
  at Spotify.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:652:16)
  at fn (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:396:10)
  at Spotify._onmessage (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:412:5)
  at WebSocket.emit (events.js:110:17)
  at Receiver.self._receiver.ontext (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:378:31)
  at Receiver.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:87:24)
  at TLSSocket.firstHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:663:22)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at TLSSocket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)
```

Do you have any clueue? Thanks!

Im running on osx 10.10.3 btw

**Comment by reneweteling** [comment]
duplicate of no 6
