### ISSUE TITLE
    throw(e); errorr

### ISSUE THREAD

**Issue by altrevino** [qrpike/spotify-playlist-downloader#15]
/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);

**Comment by fredericmalo** [comment]
Hello, yes, I got this error too : 

/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);

(newbie here, thanks)

**Comment by shushry** [comment]
Confirmed here as well (2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by edravis** [comment]
+1

**Comment by marciopamplona** [comment]
+1
/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                                  ^
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)

**Comment by scambier** [comment]
+1

**Comment by kevinhagenaars** [comment]
+1

Same error as @marciopamplona on Windows 10 x64

**Comment by ghost** [comment]
+1 mac free spotify account

**Comment by dgomesbr** [comment]
+1 on premium acc. + windows + git bash console.

**Comment by BosioGerman** [comment]
Same error on Ubuntu

/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                                  ^
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2321:27)
  at [object Object].Message.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:51)
  at Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/schemas.js:98:39)
  at Spotify._parse (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:1288:20)
  at parseData (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:592:18)
  at Spotify.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:652:16)
  at fn (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:396:10)
  at Spotify._onmessage (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:412:5)
  at WebSocket.emit (events.js:110:17)
  at Receiver.self._receiver.ontext (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:378:31)
  at Receiver.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:87:24)
  at TLSSocket.firstHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:663:22)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at TLSSocket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)

**Comment by BadChoice** [comment]
+1

**Comment by qrpike** [comment]
The error originates from here: https://github.com/TooTallNate/node-spotify-web/issues/107

You MUST _MUST_ use node version 0.10.36

If you want to change your version of node often, check out nvm ( node version manager ).

Reinstall spd once you are on the correct version of Node and it will work fine.
