### ISSUE TITLE
 Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)

### ISSUE THREAD

**Issue by rkmax** [qrpike/spotify-playlist-downloader#23]
I get the same error with node versions:
- 0.12.7
- 4.2.1

```
/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                            ^

Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:2321:27)
  at [object Object].Message.add (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:2137:51)
  at Message.decode (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper [as parse] (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/schemas.js:98:39)
  at Spotify._parse (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:1288:20)
  at parseData (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:592:18)
  at Spotify.<anonymous> (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:652:16)
  at fn (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:396:10)
  at Spotify._onmessage (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:412:5)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.self._receiver.ontext (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/Receiver.js:378:31)
  at Receiver.add (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/Receiver.js:87:24)
  at TLSSocket.firstHandler (/home/rkmax/.nvm/versions/node/v4.2.1/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/WebSocket.js:663:22)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at TLSSocket.Readable.push (_stream_readable.js:110:10)
  at TLSWrap.onread (net.js:523:20)
```

**Comment by qrpike** [comment]
Please see the other issues, it requires a specific version of node

**Comment by rkmax** [comment]
Thanks @qrpike using node 0.10.40 works.

**Comment by rkmax** [comment]
duplicate of #6
