### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by psychosteve** [qrpike/spotify-playlist-downloader#3]
What does this error mean? <pre><code>Lloyds-MBP:~ Lloyd$ npm install -g spotify-playlist-downloader
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "spotify-playlist-downloader"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /usr/local/lib/node_modules/spotify-playlist-downloader
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/spotify-playlist-downloader'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/spotify-playlist-downloader']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/spotify-playlist-downloader' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/spotify-playlist-downloader'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/local/lib/node_modules/spotify-playlist-downloader']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/spotify-playlist-downloader' }
</pre</code>

**Comment by psychosteve** [comment]
After running it in root and getting a load of protobuf issues i try an example and i get this...
<pre><code>Downloader App Started..
 - Getting Playlist Data
 - Got Playlist: ALL MUSIC
 - Processing 100 Tracks
/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                                  ^
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2321:27)
  at [object Object].Message.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:51)
  at Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/schemas.js:98:39)
  at Spotify._parse (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:1288:20)
  at parseData (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:592:18)
  at Spotify.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:652:16)
  at fn (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:396:10)
  at Spotify._onmessage (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:412:5)
  at WebSocket.emit (events.js:110:17)
  at Receiver.self._receiver.ontext (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:378:31)
  at Receiver.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:87:24)
  at TLSSocket.firstHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:663:22)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at TLSSocket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)
</pre></code>

**Comment by qrpike** [comment]
Do you have command line tools installed on your mac? You will need this for the node package dependencies, which seems like is the part that's failing.

http://railsapps.github.io/xcode-command-line-tools.html

**Comment by kwunlo** [comment]
Your node version is 0.12. You need to re-install 0.10 to get protobuf to work.
