### ISSUE TITLE
Still getting Error: Illegal value for Message.Field

### ISSUE THREAD

**Issue by benjamincharity** [qrpike/spotify-playlist-downloader#35]
I see a few posts that look like this has been solved (eg. #25) but despite all my tries this is still not working. I was able to get [spotify-ripper](https://github.com/jrnewell/spotify-ripper) working but ripping in real time is brutally slow..

I'm sure you're all tired of seeing this error.. but would anyone have any other ideas for me to try?
- Retried full install process several times
- Tried several different forks (except the window based forks - will try when home to my PC)
- Tried several different endpoints for `spotify-web` in `package.json`
  - https://github.com/fuzeman/node-spotify-web/tarball/issue/111
  - git+https://github.com/fuzeman/node-spotify-web.git
  - file:spot_node.tar.gz

``` bash
# OS X 10.11.4

$ nvm --version
0.31.0

$ node -v
v0.10.36

$ npm i -g qrpike/spotify-playlist-downloader

$ spd -u MY_USER -p MY_PASSWORD -l spotify:user:MY_USER:playlist:2q5DogTYK1DAZVlROrxG1H
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:2321:27)
  at [object Object].Message.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:2137:51)
  at Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/protobufjs/ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper [as parse] (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/schemas.js:98:39)
  at Spotify._parse (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:1288:20)
  at parseData (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:592:18)
  at Spotify.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:652:16)
  at fn (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:396:10)
  at Spotify._onmessage (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:412:5)
  at WebSocket.emit (events.js:98:17)
  at Receiver.self._receiver.ontext (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/Receiver.js:378:31)
  at Receiver.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/Receiver.js:87:24)
  at CleartextStream.firstHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/ws/lib/WebSocket.js:663:22)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:765:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickDomainCallback (node.js:486:13)
```

**Comment by benjamincharity** [comment]
fwiw just went through the install process on my windows box with no luck either..

```
# windows 10 pro

C:\Users\Benjamin>node -v
v0.10.36

C:\Users\Benjamin>spd -u MY_USER -p MY_PASSWORD -l spotify:user:spotify:playlist:6GS1XbjHjiBOFhiJHJEcMh
Downloader App Started..
 - Getting Playlist Data
 - Got Playlist: Barre Work Out
 - Processing 56 Tracks

Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:2321:27)
  at [object Object].Message.add (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:2137:51)
  at Message.decode (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper [as parse] (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\lib\schemas.js:98:39)
  at Spotify._parse (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\lib\spotify.js:1288:20)
  at parseData (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\lib\spotify.js:592:18)
  at Spotify.<anonymous> (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\lib\spotify.js:652:16)
  at fn (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\lib\spotify.js:396:10)
  at Spotify._onmessage (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\lib\spotify.js:412:5)
  at WebSocket.emit (events.js:98:17)
  at Receiver.self._receiver.ontext (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\lib\WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:391:14)
  at Receiver.expectHandler (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:378:31)
  at Receiver.add (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:87:24)
  at CleartextStream.firstHandler (C:\Users\Benjamin\nvm\v0.10.36\node_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\lib\WebSocket.js:663:22)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:765:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickDomainCallback (node.js:486:13)
```

**Comment by jesuslg123** [comment]
The same here with node v0.12.4 on Mac OS...

**Comment by gigi199596** [comment]
try installing a virtualbox with linux?
I tested it with a friend on a macintosh. Same as you... despites a correct node js version (0.10.36)

tips for the future: try using "n". It's a npm package that allow you to change node js versions in a "hot swap" way :)

**Comment by bnb** [comment]
Same here, latest OS X. Using n/latest.

**Comment by cecov74** [comment]
the same at linux centos 
node 0.10.36
how can resolve?

**Comment by giacecco** [comment]
Same here on Fedora 23 and node 4.4.4.
