### ISSUE TITLE
TypeError: Cannot read property 'csrftoken' of undefined

### ISSUE THREAD

**Issue by turbolego** [qrpike/spotify-playlist-downloader#44]
On windows 10.

```
  debug('login CSRF token: %j, tracking ID: %j', args.csrftoken, args.trackingId);
                                                      ^

TypeError: Cannot read property 'csrftoken' of undefined
    at Spotify._onsecret (C:\Users\HERPDERP\AppData\Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\spotify-web\lib\spotify.js:256:55)
    at Request.callback (C:\Users\HERPDERP\AppData\Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\superagent\lib\node\index.js:584:30)
    at Request.<anonymous> (C:\Users\HERPDERP\AppData\Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\superagent\lib\node\index.js:133:10)
    at Request.emit (events.js:132:15)
    at Request.emit (domain.js:421:20)
    at Stream.<anonymous> (C:\Users\HERPDERP\AppData\Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\superagent\lib\node\index.js:714:12)
    at Stream.emit (events.js:132:15)
    at Stream.emit (domain.js:421:20)
    at Unzip.<anonymous> (C:\Users\HERPDERP\AppData\Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\superagent\lib\node\utils.js:120:12)
    at Unzip.emit (events.js:132:15)
    at Unzip.emit (domain.js:421:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by ayushzenith** [comment]
same issue do u have a fix???

**Comment by jimb-cc** [comment]
Yes, Seeing that here too.  CSRF is the Cross-Site Request Forgery token which Spotify have probably fairly recently introduced or changed.

**Comment by riemerick** [comment]
Exactly the same error here.
Waiting a solution to test spotify-playlist-downloader.

**Comment by arneschlag** [comment]
Still the same error here. 
Also waiting for a solution

**Comment by EudrinoDev** [comment]
Same Error, waiting for a solution

**Comment by spencerthayer** [comment]
Same error, waiting for solution.

**Comment by vergissberlin** [comment]
Last update seven years ago …
