### ISSUE TITLE
Error: Illegal value

### ISSUE THREAD

**Issue by invmatt** [qrpike/spotify-playlist-downloader#6]
Gets the playlist data then produces this error:

> Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catal
ogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (C:\Users\matt.otley\App
Data\Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\spotify-w
eb\node_modules\protobufjs\ProtoBuf.js:2321:27)
  at [object Object].Message.add (C:\Users\matt.otley\AppData\Roaming\npm\node_m
odules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\protobu
fjs\ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (C:\Users\matt.otley\AppDat
a\Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\spotify-web\
node_modules\protobufjs\ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (C:\Users\matt.otley\AppData\
Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\spotify-web\no
de_modules\protobufjs\ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (C:\Users\matt.otley\AppDat
a\Roaming\npm\node_modules\spotify-playlist-downloader\node_modules\spotify-web\
node_modules\protobufjs\ProtoBuf.js:2137:51)
  at Message.decode (C:\Users\matt.otley\AppData\Roaming\npm\node_modules\spotif
y-playlist-downloader\node_modules\spotify-web\node_modules\protobufjs\ProtoBuf.
js:1982:41)
  at Function.protobufjs_parse_wrapper [as parse] (C:\Users\matt.otley\AppData\R
oaming\npm\node_modules\spotify-playlist-downloader\node_modules\spotify-web\lib
\schemas.js:98:39)
  at Spotify._parse (C:\Users\matt.otley\AppData\Roaming\npm\node_modules\spotif
y-playlist-downloader\node_modules\spotify-web\lib\spotify.js:1288:20)
  at parseData (C:\Users\matt.otley\AppData\Roaming\npm\node_modules\spotify-pla
ylist-downloader\node_modules\spotify-web\lib\spotify.js:592:18)
  at Spotify.<anonymous> (C:\Users\matt.otley\AppData\Roaming\npm\node_modules\s
potify-playlist-downloader\node_modules\spotify-web\lib\spotify.js:652:16)
  at fn (C:\Users\matt.otley\AppData\Roaming\npm\node_modules\spotify-playlist-d
ownloader\node_modules\spotify-web\lib\spotify.js:396:10)
  at Spotify._onmessage (C:\Users\matt.otley\AppData\Roaming\npm\node_modules\sp
otify-playlist-downloader\node_modules\spotify-web\lib\spotify.js:412:5)
  at WebSocket.emit (events.js:98:17)
  at Receiver.self._receiver.ontext (C:\Users\matt.otley\AppData\Roaming\npm\nod
e_modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\l
ib\WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (C:\Users\matt.otley\AppData\Roaming\npm\node_mod
ules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\lib\Re
ceiver.js:391:14)
  at Receiver.expectHandler (C:\Users\matt.otley\AppData\Roaming\npm\node_module
s\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\lib\Recei
ver.js:378:31)
  at Receiver.add (C:\Users\matt.otley\AppData\Roaming\npm\node_modules\spotify-
playlist-downloader\node_modules\spotify-web\node_modules\ws\lib\Receiver.js:87:
24)
  at CleartextStream.firstHandler (C:\Users\matt.otley\AppData\Roaming\npm\node_
modules\spotify-playlist-downloader\node_modules\spotify-web\node_modules\ws\lib
\WebSocket.js:663:22)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:764:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at _stream_readable.js:419:7
  at process._tickDomainCallback (node.js:463:13)

**Comment by qrpike** [comment]
I don't have a windows machine to test on, please let me know if you solve the issue.

Thanks,

**Comment by jeremy89632** [comment]
Same issue on the mac too, here goes:

 - Processing 100 Tracks
/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                                  ^
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2321:27)
  at [object Object].Message.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:51)
  at Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/schemas.js:98:39)
  at Spotify._parse (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:1288:20)
  at parseData (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:592:18)
  at Spotify.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:652:16)
  at fn (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:396:10)
  at Spotify._onmessage (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:412:5)
  at WebSocket.emit (events.js:110:17)
  at Receiver.self._receiver.ontext (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:378:31)
  at Receiver.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:87:24)
  at TLSSocket.firstHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:663:22)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at TLSSocket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)

**Comment by bernhardmostrey** [comment]
same issue!

Downloader App Started..
 - Getting Playlist Data
 - Got Playlist: R&B Stars
 - Processing 50 Tracks
/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                                  ^
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2321:27)
  at [object Object].Message.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:51)
  at Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/schemas.js:98:39)
  at Spotify._parse (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:1288:20)
  at parseData (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:592:18)
  at Spotify.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:652:16)
  at fn (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:396:10)
  at Spotify._onmessage (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:412:5)
  at WebSocket.emit (events.js:110:17)
  at Receiver.self._receiver.ontext (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:378:31)
  at Receiver.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:87:24)
  at TLSSocket.firstHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:663:22)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at TLSSocket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)

**Comment by jrvmbust** [comment]
Same thing happens to mine, tried downgrading node via nvm to 0.10.36 but still no avail. Help?

**Comment by CaptainShadows** [comment]
Same issue on node 0.12.4

**Comment by ashkanalinejad** [comment]
I have the same issue on my mac. but I think it's a consequence of not having a premium account

**Comment by tristan1990** [comment]
Yes, that could be it - I have premium.

**Comment by roshanr10** [comment]
@tristan1990 it only works on node v10. Have you been able to solve the issue?

**Comment by reneweteling** [comment]
Hey there,

Nice app btw. only im receiving an error when trying to download a link.

```
Downloader App Started..
 - Getting Playlist Data
 - Got Playlist: OLD SCHOOL HIP HOP
 - Processing 100 Tracks
/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                                  ^
Error: Illegal value for Message.Field .spotify.metadata.proto.Restriction.catalogue: 4 (not a valid enum value)
  at [object Object].ProtoBuf.Reflect.Field.verifyValue (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2321:27)
  at [object Object].Message.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1693:53)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:29)
  at [object Object].ProtoBuf.Reflect.Field.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2594:46)
  at [object Object].ProtoBuf.Reflect.Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:2137:51)
  at Message.decode (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1982:41)
  at Function.protobufjs_parse_wrapper (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/schemas.js:98:39)
  at Spotify._parse (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:1288:20)
  at parseData (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:592:18)
  at Spotify.<anonymous> (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:652:16)
  at fn (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:396:10)
  at Spotify._onmessage (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/lib/spotify.js:412:5)
  at WebSocket.emit (events.js:110:17)
  at Receiver.self._receiver.ontext (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:391:14)
  at Receiver.expectHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:378:31)
  at Receiver.add (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/Receiver.js:87:24)
  at TLSSocket.firstHandler (/usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/ws/lib/WebSocket.js:663:22)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at TLSSocket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)
```

Do you have any clueue? Thanks!

Im running on osx 10.10.3 btw

**Comment by reneweteling** [comment]
Ok solved it, you nee node v.0.10.0 
just install https://www.npmjs.com/package/n
install v.0.10.0 and go :)

**Comment by jperezr21** [comment]
Same error here. Changed to node v0.10.0 but it's still happening.
Any other solution? Thanks!

**Comment by reneweteling** [comment]
@jperezr21 what os are you using, and what does node say when you do `node -v`?

**Comment by jperezr21** [comment]
@reneweteling I'm on windows 7 and using nodist for managing node versions. I downloaded v0.10.0 and when I type node -v it says v0.10.0. Still, I thought it might be using another version, so I uninstalled the others, but the error is still there.

**Comment by reneweteling** [comment]
@jperezr21 hmmmm..... wel windows is an issue by default... me recommendation is to boot up a virtual box, install ubuntu and try it there in the terminal. Its a bit of a way around.... but thats probably your best bet. Good luck!

**Comment by gtothesquare** [comment]
@jperezr21 try uninstalling everything related to node. You need to install the downloader with node 0.10.x if not your protobufjs will not work properly

**Comment by ozgurduygu** [comment]
I struggled with the same issue and here's the solution that I came with: 
uninstall node.js completely
install 0.10.36  http://nodejs.org/dist/v0.10.36
make sure you have installed brew and ffmpeg

**Comment by sgarwang** [comment]
I got the same error, got work around by using 0.10.36~ Thanks!

Downloader App Started..
- Getting Playlist Data
- Got Playlist: OLD SCHOOL HIP HOP
- Processing 100 Tracks
  /usr/local/lib/node_modules/spotify-playlist-downloader/node_modules/spotify-web/node_modules/protobufjs/ProtoBuf.js:1987
                          throw(e);
